---
# Part: Pound
#
# Description: Concatenate a certificate file and a private key file into a
# combined certificate as required by pound.
#
# Parameters:
# - certificate
# - private_key
# - output: Certificate to output, should end with .pem
#
# Dependencies:
#
# Creates:
# - {{ output }}
#
# File modifications:
#
###############################################################################

- name: "certificate | Create a storage directory for combined pem files: /etc/ssl/combined"
  file:
    path=/etc/ssl/combined
    state=directory
    owner=root group=root mode=0700
  tags:
    - certificate-combined

- name: certificate | Check current certificate md5sum
  shell:
    md5sum {{ output }}
  ignore_errors: true
  changed_when: false
  register: certificate_md5sum
  tags:
    - certificate-combined

- name: "certificate | Join certificate and private key into one"
  shell:
    cat {{ certificate }} {{ private_key }} >| {{ output }}; cat {{ output }}
  register: combined_md5sum
  changed_when: certificate_md5sum.stdout != combined_md5sum.stdout
  tags:
    - certificate-combined

- name: "certificate | Set certificate permissions"
  file:
    path={{ output }}
    mode=0700
    owner=root group=root
  tags:
    - certificate-combined
