---
# Part: Pound
#
# Description:
#
# Parameters:
#
# Dependencies:
# - tasks:join-cert-key
# - ufw:tasks:entry
#
# Creates:
#
# File modifications:
# - /usr/local/etc/pound.cfg
#
###############################################################################

- name: install | Install package pound
  apt:
    pkg={{ item }}
    state=present
  with_items:
    - ssl-cert
    - pound
  tags:
    - install

- include: join-cert-key.yml
  vars:
    certificate: '{{ pound.ssl.certificate }}'
    private_key: '{{ pound.ssl.private_key }}'
    output: '{{ pound.ssl.combined_cert }}'
  when: pound.join_cert_key
  tags:
    - config

- name: "config | Configure Pound: /usr/local/etc/pound.cfg"
  template:
    src=pound.cfg.j2
    dest=/etc/pound/pound.cfg
    owner=root group=root
  notify: restart pound
  tags:
    - config

# General management
###

- include: ../../common/tasks/service.yml
  vars:
    name: pound
    enabled: '{{ pound.enabled }}'
    set_default: true

- include: ../../monit/tasks/entry.yml
  vars:
    name: pound
    port: '{{ pound.port }}'
    enabled: '{{ pound.enabled }}'

- include: ../../logrotate/tasks/entry.yml
  vars:
    name: pound
    logs: '{{ pound.log.file }}'
    size: 100M
    maxage: 30
    enabled: '{{ pound.enabled }}'

- include: ../../rsyslog/tasks/entry.yml
  vars:
    name: pound
    mode: facility
    facility: local6.*
    enabled: '{{ pound.enabled }}'
    output: '{{ pound.log.file }}'

- include: ../../ufw/tasks/entry.yml
  vars:
    name: '{{ pound.port }}'
    enabled: '{{ pound.enabled }}'
