---
- name: restart apache
  service:
    name=apache2
    state=restarted

- name: reload apache
  service:
    name=apache2
    state=reloaded

- name: lint apache
  command: apachectl configtest
  changed_when: false
