---
drush:
  # Also required by package.yml
  dir: /etc/drush

  dev:
    install: true
    modules:
      - cacheaudit
      - drush-hosts
      - clean_missing_modules
      - module_builder
      - coder
      - registry_rebuild

  config:
    dump_dir: '/etc/drush/dump'
    alias_dir: '/etc/drush/aliases'

  # alias.yml
  staging:
    path: /var/www/staging
