---
# Part: Rsyslog
#
# Description: Set up and configure rsyslog
#
# Parameters:
#
# Dependencies:
#
# Creates:
#
# File modifications:
# - /etc/rsyslog.conf
# - /var/spool/rsyslog
#
###############################################################################

- name: install | Install rsyslog package
  apt:
    pkg=rsyslog
    state=present
  tags:
    - rsyslog-config

- name: "config | Configure: /etc/rsyslog.conf"
  template:
    src=rsyslog.conf.j2
    dest=/etc/rsyslog.conf
    owner=root group=root
  notify: restart rsyslog
  tags:
    - rsyslog-config

- name: "config | Set owner to syslog: /var/spool/rsyslog"
  file:
    path=/var/spool/rsyslog
    owner={{ rsyslog.owner }} group={{ rsyslog.group }}
  notify: restart rsyslog
  tags:
    - rsyslog-config

- include: loggly.yml
  when: rsyslog.loggly.enabled

- name: lint | Verify configuration
  command: rsyslogd -N1
  changed_when: false
  tags:
    - lint

# General management
###

- include: ../../common/tasks/service.yml
  vars:
    name: rsyslog
  tags:
    - rsyslog-config

- include: ../../monit/tasks/entry.yml
  vars:
    name: rsyslog
    enabled: '{{ rsyslog.enabled }}'
  tags:
    - rsyslog-config
