---
# Part: Apache
#
# Description: Creates an apache virtual host with an optional docroot.
#
# Parameters:
# - create_docroot: Whether to create the document root (default: true)
# - docroot: The location of document root, eg. /var/www/foo.com
# - docroot_options: The options string for the docroot (default: -Index -Multiviews)
# - vhost: Virtual host name, eg. foo.com
# - local_only: Whether the virtual host is accessable to localhost only (default: false)
# - admin: The apache administrator (default: admin@localhost)
# - vhost_server_alias: Optional alias to use (default: www.{{ vhost }} if the vhost doesnt start with www))
# - vhost_include: Optional list of files to include (default: [])
# - ssl.enabled: Whether SSL is enabled (default: false)
# - ssl.only: Whether to force SSL (default: false)
# - ssl.certificate_file: Path to SSL certificate (default: {{ snakeoil_certificate_file }})
# - ssl.certificate_key_file: Path to SSL certificate key (default: {{ snakeoil_certificate_key_file }}
# - ssl.certificate_chain_file: Path to SSL certificate chain file (default: false)
# - ssl.options: SSL options to use (defaults: +FakeBasicAuth +StrictRequire)
#
# Dependencies:
# - defaults:main
# - tasks:main
#
# Creates:
# - /etc/apache2/sites-available/{{ vhost }}
# - /etc/apache2/sites-enabled/{{ vhost }}
#
# File modifications:
#
###############################################################################

- name: Apache | Create document root at {{ docroot }}
  file:
    path={{ docroot }}
    state=directory
  when: create_docroot
  tags:
    - apache
    - vhost

- name: Apache | Add virtual host configuration for {{ vhost }}: /etc/apache2/sites-available/{{ vhost }}
  template:
    src=virtualhost.j2
    dest=/etc/apache2/sites-available/{{ vhost }}
  tags:
    - apache
    - vhost

- name: Apache | Activate virtual host {{ vhost }}: /etc/apache2/sites-enabled/{{ vhost }}
  command:
    a2ensite {{ vhost }}
    creates=/etc/apache2/sites-enabled/{{ vhost }}
  notify: reload apache
  tags:
    - apache
    - vhost
