---
# Part: Apache
#
# Description: Manage a vhost for local only access. Subsequent runs will add aliases
# into the vhost.
#
# Parameters:
# - alias: The alias to add, eg. /apc
# - docroot: The destination docroot, eg. /opt/apc
# - enabled (default: true)
#
# Dependencies:
# - tasks:main
#
# Creates:
# - /etc/apache2/sites-available/{{ local_vhost.vhost }}
# - /etc/apache2/sites-enabled/{{ local_vhost.vhost }}
# - {{ local_vhost.url }}: Localhost only accessable virtual host
#
# File modifications:
# - /etc/apache2/vhosts.d/{{ local_vhost.vhost }}.conf
#
###############################################################################

- name: "local vhost | Create local vhost docroot"
  file:
    path={{ local_vhost.docroot }}
    state=directory
    owner=root group=root
  tags:
    - apache

- name: "local vhost | config | Create a vhost specific config: /etc/apache2/vhosts.d/{{ local_vhost.vhost }}.conf"
  copy:
    src=per-vhost.conf
    dest=/etc/apache2/vhosts.d/{{ local_vhost.vhost }}.conf
    owner=root group=root
    force=no
  tags:
    - apache

- name: "local vhost | config | Add virtual host configuration for {{ local_vhost.vhost }}: /etc/apache2/sites-available/{{ local_vhost.vhost }}"
  template:
    src=virtualhost-local.j2
    dest=/etc/apache2/sites-available/{{ local_vhost.vhost }}
    owner=root group=root
  tags:
    - apache

- name: "local vhost | enable | Add an alias for {{ alias }} to {{ docroot }}: /etc/apache2/vhosts.d/{{ local_vhost.vhost }}.conf"
  lineinfile:
    dest=/etc/apache2/vhosts.d/{{ local_vhost.vhost }}.conf
    regexp="^Alias {{ alias }}"
    line="Alias {{ alias }} {{ docroot }}"
  when: enabled|default(true)|bool
  notify: restart apache
  tags:
    - apache

- name: "local vhost | disable | Remove alias for {{ alias }}: /etc/apache2/vhosts.d/{{ local_vhost.vhost }}.conf"
  lineinfile:
    dest=/etc/apache2/vhosts.d/{{ local_vhost.vhost }}.conf
    regexp="^Alias {{ alias }}"
    state=absent
  when: not enabled|default(true)|bool
  notify: restart apache
  tags:
    - apache

- name: "local vhost | enable | Activate virtual host {{ local_vhost.vhost }}: /etc/apache2/sites-enabled/{{ local_vhost.vhost }}"
  command:
    a2ensite {{ local_vhost.vhost }}
    creates=/etc/apache2/sites-enabled/{{ local_vhost.vhost }}
  notify: reload apache
  tags:
    - apache
