---
# Part: Apache
#
# Description: Creates an apache virtual host with an optional docroot.
#
# Parameters:
# - enabled (default: true)
# - vhost
# - server_alias
# - include
# - docroot
# - docroot_options (default: -Indexes -MultiViews)
# - ssl.enabled (default: false)
# - ssl.certificate_file
# - ssl.certificate_key_file
# - ssl.certificate_chain_file
# - ssl.options (default: +FakeBasicAuth +StrictRequire)
# - purge (default: false)
#
# Dependencies:
# - tasks:main
#
# Creates:
# - /etc/apache2/sites-available/{{ vhost }}
# - /etc/apache2/sites-enabled/{{ vhost }}
#
# File modifications:
#
###############################################################################


# Create
###
- name: "vhost | enable | Create document root: {{ docroot }}"
  file:
    path={{ docroot }}
    state=directory
  when: enabled|default(true)|bool
  tags:
    - vhost
    - enable

- name: "vhost | enable | Add virtual host configuration for {{ vhost }}: /etc/apache2/sites-available/{{ vhost }}"
  template:
    src=virtualhost.j2
    dest=/etc/apache2/sites-available/{{ vhost }}
    owner=root group=root
  when: enabled|default(true)|bool
  tags:
    - vhost
    - enable

- name: "vhost | enable | Activate virtual host {{ vhost }}: /etc/apache2/sites-enabled/{{ vhost }}"
  command:
    a2ensite {{ vhost }}
    creates=/etc/apache2/sites-enabled/{{ vhost }}
  notify: reload apache
  when: enabled|default(true)|bool
  tags:
    - vhost
    - enable

# Remove
###

- name: "vhost | disable | Remove document root: {{ docroot }}"
  file:
    path={{ docroot }}
    state=absent
  when: not enabled|default(true)|bool and purge|default(false)|bool
  tags:
    - apache
    - vhost
    - disable

- name: "vhost | disable | Deactivate virtual host {{ vhost }}: /etc/apache2/sites-enabled/{{ vhost }}"
  command:
    a2dissite {{ vhost }}
    removes=/etc/apache2/sites-enabled/{{ vhost }}
  when: not enabled|default(true)|bool
  notify: reload apache
  tags:
    - apache
    - vhost
    - disable

- name: "vhost | disable | Remove virtual host configuration: /etc/apache2/sites-available/{{ vhost }}"
  file:
    path=/etc/apache2/sites-available/{{ vhost.name }}
    state=absent
  when: not enabled|default(true)|bool and purge|default(false)|bool
  tags:
    - apache
    - vhost
    - disable

- name: "vhost | disable | Remove per virtual host include configuration: /etc/apache2/vhosts.d/{{ vhost }}.conf"
  file:
    path=/etc/apache2/vhosts.d/{{ vhost }}.conf
    state=absent
  when: not enabled|default(true)|bool and purge|default(false)|bool
  tags:
    - apache
    - vhost
    - disable
