---
# Job: Setup
#
# Description: Manages all development servers
#
###############################################################################

- hosts: development
  sudo: true
  connection: '{{ connection|default("ssh") }}'
  vars:
    hostname: '{{ ansible_hostname }}'
    ip: '{{ ansible_venet0_0.ipv4.address }}'
    notify_email: ['public@oxy.fi', 'christoffer.bjorkskog@genero.fi']
    virtualization: '{{ ansible_virtualization_type  }}'

  roles:
    # Make sure admin users exist
    - { role: common, tags: ['common'] }
    - { role: user, tags: ['user'] }
    - { role: ufw, tags: ['ufw '] }
    - { role: monit, tags: ['monit '] }
    - { role: rsyslog, tags: ['rsyslog '] }
    - { role: postfix, tags: ['postfix '] }
    - { role: apache, tags: ['apache '] }
    - { role: development, tags: ['development '] }
    - { role: php, tags: ['php '] }
    - { role: mariadb, tags: ['mariadb '] }
    - { role: drush, tags: ['drush '] }
    - { role: wpcli, tags: ['wpcli '] }
    - { role: varnish, tags: ['varnish '] }
    - { role: pound, tags: ['pound '] }
    - { role: vnstat, tags: ['vnstat '] }
    - { role: security, tags: ['security '] }
    - { role: newrelic, tags: ['newrelic '] }
    - { role: project, tags: ['project '] }
