---
# Job: Setup
#
# Description: Manages all the servers
#
###############################################################################

- hosts: development
  remote_user: oxy # @TODO
  sudo_user: oxy
  vars:
    hostname: {{ ansible_hostname }}
    ip: {{ ansible_eth0.ipv4.address }}
    # Global flag for apache, mariadb, php
    development: true
    notify_email: public@oxy.fi
    email:
      # This should be used to get fast notifications
      monit:
        enabled: true
        alerts: []
        timeouts: []
      # Disabled in favour of logstash
      logwach:
        mail:
          enabled: false
          notify_email: ''
      # Uses syslogd instead
      denyhosts:
        mail:
          enabled: false
          notify_email: ''
      # Not in syslogd
      # Set to false to disable cron
      rootkit:
        notify_email: {{ notify_email }}

  vars_files:
    - vars/settings.yml
  roles:
    # Make sure admin users exist
    - { role: user, active: admins_active, departed: admins_departed, user_groups: admin_groups }
    # Make sure regular users exist
    - { role: user, active: users_active, departed: users_departed, user_groups: user_groups }
    # Make sure managed users exist and have correct passwords.
    - { role: user, managed: managed }
    - { role: common }
    - { role: mail }
    - { role: monit }
    - { role: development }
    - { role: apache }
    - { role: php }
    - { role: mariadb, active: mariadb_active, departed: mariadb_departed }
    - { role: drush }
    - { role: wpcli }
    - { role: varnish }
    - { role: pound }
    - { role: security }
    - { role: rsyslog }
    - { role: logwatch }
    - { role: newrelic }
