---
# Part: User
#
# Description: Create a set of user accounts
#
# Parameters:
# - users: A list of user dictionaries, each with the properties:
#   username, fullname, email
# - user_groups: A list of default groups to add the users to.
#
# Dependencies:
# - tasks:main
#
# Creates:
#
# File modifications:
#
###############################################################################

- name: "Create user groups"
  group:
    name={{ item }}
    state=present
  with_items: user_groups
  tags:
    - user-create
    - user-groups

- name: Create user accounts (without passwords)
  user:
    name="{{ item.username }}"
    comment="{{ item.fullname }}"
    groups="{{ user_groups|join(',') }}"
    generate_ssh_key=yes
    ssh_key_comment={{ item.email }}
    state=present
  with_items: '{{ users|rejectattr("password")|list }}'
  tags:
    - user-create

- name: Create user accounts (with passwords)
  user:
    name="{{ item.username }}"
    comment="{{ item.fullname }}"
    groups="{{ user_groups|join(',') }}"
    generate_ssh_key=yes
    ssh_key_comment={{ item.email }}
    state=present
    password={{ item.password }}
    update_password=on_create
  with_items: '{{ users|selectattr("password")|list }}'
  tags:
    - user-create

- include: set-user-permissions.yml
  tags:
    - user-create
