---
# Part: User
#
# Description: Create a set of user accounts
#
# Parameters:
# - users: A list of user dictionaries, each with the properties:
#   username, fullname
# - user_group: A comma delimited list of default groups to add the users to.
#
# Dependencies:
# - tasks:main
#
# Creates:
#
# File modifications:
#
###############################################################################

- name: User | Create user accounts
  user:
    name={{ item.username }}
    comment={{ item.fullname }}
    groups={{ user_groups }}
    generate_ssh_key=yes
    ssh_key_bits=2048
    state=present
  with_items: users

- include: set-user-permissions.yml
