---
# Part: User
#
# Description: Create a set of user accounts
#
# Parameters:
# - users: A list of user dictionaries, each with the properties:
#   username, fullname, groups
#
# Dependencies:
# - tasks:main
#
# Creates:
# - /home/{{ username }}
# - /home/{{ username }}/.ssh
# - /home/{{ username }}/.ssh/authorized_keys
#
# File modifications:
#
###############################################################################

- name: User | Managed | Create user accounts
  user:
    name={{ item.username }}
    comment={{ item.fullname }}
    groups={{ item.groups }}
    password={{ lookup('password', 'credentials/' + hostname + '/' + item.username + '/user_password length=15 encrypt=sha512_crypt') }}
    generate_ssh_key=yes
    ssh_key_bits=2048
    state=present
  with_items: users

- name: User | Managed | Set home file permissions
  file:
    path=/home/{{ item.username }}
    owner={{ item.username }}
    group={{ item.username }}
    mode=0700
    state=directory
  with_items: users
  tags:
    - security
    - permissions

- name: User | Managed | Set SSH folder permissions
  file:
    path=/home/{{ item.username }}/.ssh
    owner={{ item.username }}
    group={{ item.username }}
    mode=0700
    state=directory
  with_items: users
  tags:
    - ssh
    - security
    - permissions

- name: User | Managed | Set SSH authorized_keys permissions
  file:
    path=/home/{{ item.username }}/.ssh/authorized_keys
    mode=0600
  with_items: users
  tags:
    - ssh
    - security
    - permissions
