---
# Part: User
#
# Description: Create a set of user accounts
#
# Parameters:
# - users: A list of user dictionaries, each with the properties:
#   username, fullname, groups, email
#
# Dependencies:
# - tasks:main
#
# Creates:
#
# File modifications:
#
###############################################################################

- name: Managed users | Create user groups
  group:
    name={{ item[1] }}
    state=present
  with_subelements:
    - users
    - groups
  tags:
    - user-groups

- name: Managed users | Create user accounts
  user:
    name="{{ item.username }}"
    comment="{{ item.fullname }}"
    groups="{{ item.groups|join(',') }}"
    password={{ lookup('password', inventory_dir + '/credentials/' + ansible_hostname + '/' + item.username + '/user_password length=15 encrypt=sha512_crypt') }}
    generate_ssh_key=yes
    ssh_key_comment={{ item.email }}
    update_password=always
    state=present
  with_items: users
  tags:
    - user-create

- include: set-user-permissions.yml
  tags:
    - user-create
