---
# Part: User
#
# Description: Create a set of user accounts
#
# Parameters:
# - users: A list of user dictionaries, each with the properties:
#   username, fullname, groups
#
# Dependencies:
# - tasks:main
#
# Creates:
#
# File modifications:
#
###############################################################################

- name: User | Managed | Create user accounts
  user:
    name={{ item.username }}
    comment={{ item.fullname }}
    groups={{ item.groups }}
    password={{ lookup('password', 'credentials/' + hostname + '/' + item.username + '/user_password length=15 encrypt=sha512_crypt') }}
    generate_ssh_key=yes
    ssh_key_bits=2048
    state=present
  with_items: users

- include: set-user-permissions.yml
