---
# Part: User
#
# Description: Create a set of user accounts
#
# Parameters:
# - users: A list of user dictionaries, each with the properties:
#   username, fullname
# - user_group: A comma delimited list of default groups to add the users to.
#
# Dependencies:
# - tasks:main
#
# Creates:
# - /home/{{ username }}
# - /home/{{ username }}/.ssh
# - /home/{{ username }}/.ssh/authorized_keys
#
# File modifications:
#
###############################################################################

- name: User | Create user accounts
  user:
    name={{ item.username }}
    comment={{ item.fullname }}
    groups={{ user_groups }}
    generate_ssh_key=yes
    ssh_key_bits=2048
    state=present
  with_items: users

- name: User | Set home file permissions
  file:
    path=/home/{{ item.username }}
    owner={{ item.username }}
    group={{ item.username }}
    mode=0700
    state=directory
  with_items: users
  tags:
    - security
    - permissions

- name: User | Set SSH folder permissions
  file:
    path=/home/{{ item.username }}/.ssh
    owner={{ item.username }}
    group={{ item.username }}
    mode=0700
    state=directory
  with_items: users
  tags:
    - ssh
    - security
    - permissions

- name: User | Set SSH authorized_keys permissions
  file:
    path=/home/{{ item.username }}/.ssh/authorized_keys
    mode=0600
  with_items: users
  tags:
    - ssh
    - security
    - permissions
