---
# Part: User
#
# Description: Manage active and departed users of a single group type. This
# should most likely be included twice, once for administrative users and once
# for regular users.
#
# Parameters:
#
# Dependencies:
#
# Creates:
#
# File modifications:
#
###############################################################################

- name: Set default shell to /bin/bash
  command: useradd -D -s /bin/bash
  changed_when: false
  tags:
    - config

# Admins
###
- include: create-users.yml
  vars:
    users: '{{ user_accounts.admins.active }}'
    user_groups: '{{ user_accounts.admins.groups }}'

- include: dotfiles.yml
  vars:
    users: '{{ user_accounts.admins.active }}'

- include: delete-users.yml
  vars:
    users: '{{ user_accounts.admins.departed }}'

# Regular
###

- include: create-users.yml
  vars:
    users: '{{ user_accounts.regular.active }}'
    user_groups: '{{ user_accounts.regular.groups }}'

- include: dotfiles.yml
  vars:
    users: '{{ user_accounts.regular.active }}'

- include: delete-users.yml
  vars:
    users: '{{ user_accounts.regular.departed }}'

# Managed
###

- include: create-managed-users.yml
  vars:
    users: '{{ user_accounts.managed }}'

- include: dotfiles.yml
  vars:
    users: '{{ user_accounts.managed }}'
