---
# Part: User
#
# Description: Create a set of user accounts
#
# Parameters:
# - users: A list of user dictionaries, each with the properties:
#   username
#
# Dependencies:
# - tasks:main
#
# Creates:
#
# File modifications:
# - /home/{{ username }}
# - /home/{{ username }}/.ssh
# - /home/{{ username }}/.ssh/authorized_keys
# - /home/{{ username }}/.ssh/known_hosts
#
###############################################################################
- name: Set home file permissions ~/
  file:
    path=/home/{{ item.username }}
    owner={{ item.username }} group={{ item.username }} mode=0700
    state=directory
  with_items: users
  tags:
    - user-permissions

- name: Set SSH folder permissions ~/.ssh
  file:
    path=/home/{{ item.username }}/.ssh
    owner={{ item.username }} group={{ item.username }} mode=0700
    state=directory
  with_items: users
  tags:
    - user-permissions

- name: Create ~/.ssh/authorized_keys
  copy:
    src=authorized_keys
    dest=/home/{{ item.username }}/.ssh/authorized_keys
    owner={{ item.username }} group={{ item.username }} mode=0600
    force=no
  with_items: users
  tags:
    - user-permissions

- name: Set SSH authorized_keys permissions ~/.ssh/authorized_keys
  file:
    path=/home/{{ item.username }}/.ssh/authorized_keys
    owner={{ item.username }} group={{ item.username }} mode=0600
    state=file
  with_items: users
  tags:
    - user-permissions

- name: Create ~/.ssh/known_hosts
  copy:
    src=known_hosts
    dest=/home/{{ item.username }}/.ssh/known_hosts
    owner={{ item.username }} group={{ item.username }} mode=0644
    force=no
  with_items: users
  tags:
    - user-known-hosts

- name: Set SSH known_hosts permissions ~/.ssh/known_hosts
  file:
    path=/home/{{ item.username }}/.ssh/known_hosts
    owner={{ item.username }} group={{ item.username }} mode=0644
    state=file
  with_items: users
  tags:
    - user-known-hosts

- name: Add known hosts to ~/.ssh/known_hosts
  lineinfile:
    dest=/home/{{ item[0].username }}/.ssh/known_hosts
    regexp="^{{ item[1].host }}"
    line="{{ item[1].line }}"
    state=present
  with_nested:
    - users
    - user.known_hosts
  tags:
    - user-known-hosts
