---
# Part: Monit
#
# Description: Set up monit mail
#
# Parameters:
#
# Dependencies:
#
# Creates:
#
# File modifications:
# - /etc/monit/conf.d/mail
#
###############################################################################

- name: "mail | Setup mail: /etc/monit/conf.d/mail"
  template:
    src=mail.j2
    dest=/etc/monit/conf.d/mail
  notify:
    - lint monit
    - restart monit
  when: monit.mail.enabled
  tags:
    - monit-mail

- name: "mail | Disable mail: /etc/monit/conf.d/mail"
  file:
    path=/etc/monit/conf.d/mail
    state=absent
  notify: restart monit
  when: not monit.mail.enabled
  tags:
    - monit-mail
