---
# Part: Monit
#
# Description: Set up monit mail
#
# Parameters:
# - mail.enabled: Whether email notifications should be enabled (default: false)
# - mail.alerts: List of mail addresses to email on alerts (default: [])
# - mail.timeouts: List of mail addresses to email on timeouts (default: [])
#
# Dependencies:
#
# Creates:
#
# File modifications:
# - /etc/monit/conf.d/mail
#
###############################################################################
- name: Monit | Setup mail: /etc/monit/conf.d/mail
  template:
    src=mail.j2
    dest=/etc/monit/conf.d/mail
  notify: restart monit
  when: mail.enabled
  tags:
    - config
    - enable

- name: Monit | Disable mail: delete /etc/monit/conf.d/mail
  file:
    path=/etc/monit/conf.d/mail
    state=absent
  notify: restart monit
  when: not mail.enabled
  tags:
    - config
    - disable
