---
# Part: Monit
#
# Description: Set up monit
#
# Parameters:
#
# Dependencies:
#
# Creates:
#
# File modifications:
# - /etc/default/monit
# - /etc/monit/conf.d/{{ services }}
# - /etc/monitrc
#
###############################################################################

- name: install | Install monit package
  apt:
    pkg=monit
    state=present
  tags:
    - monit-config

- name: "config | Configure monit: /etc/monitrc"
  template:
    src=monitrc.j2
    dest=/etc/monit/monitrc
    owner=root group=root
  notify:
    - lint monit
    - restart monit
  tags:
    - monit-config

- include: webinterface.yml
  when: monit.webinterface.install

- include: mail.yml
  when: monit.mail.install

# General management
###

- include: ../../common/tasks/service.yml
  vars:
    name: monit
    enabled: "{{ monit.enabled }}"
    set_default: true
  tags:
    - monit-config

- include: ../../logrotate/tasks/entry.yml
  vars:
    name: monit
    logs: '{{ monit.log.file }}'
    special: weekly
    maxage: 30
    enabled: "{{ monit.enabled }}"
  tags:
    - monit-config

- include: ../../rsyslog/tasks/entry.yml
  vars:
    name: monit
    mode: facility
    facility: '{{ monit.log.facility }}.*'
    output: '{{ monit.log.file }}'
    enabled: "{{ monit.enabled }}"
  tags:
    - monit-config
