---
# Part: Monit
#
# Description: Set up monit webinterface
#
# Parameters:
#
# Dependencies:
# - tasks:main
#
# Creates:
#
# File modifications:
# - /etc/monit/conf.d/webinterface
#
###############################################################################

- name: "webinterface | Configure: /etc/monit/conf.d/webinterface"
  template:
    src=webinterface.j2
    dest=/etc/monit/conf.d/webinterface
    owner=root group=root
  notify: restart monit
  when: monit.webinterface.enabled
  tags:
    - webinterface
    - monit

- name: "webinterface | Disable webinterface: /etc/monit/conf.d/webinterface"
  file:
    path=/etc/monit/conf.d/webinterface
    state=absent
  notify: restart monit
  when: not monit.webinterface.enabled
  tags:
    - webinterface
    - monit

- name: webinterface | Add groups
  group:
    name={{ item }}
    state=present
  with_items:
    - monit.webinterface.rw_group
    - monit.webinterface.r_group
  tags:
    - webinterface
    - monit

- include: ../../pound/tasks/join-cert-key.yml
  vars:
    certificate: '{{ monit.ssl.certificate }}'
    private_key: '{{ monit.ssl.private_key }}'
    output: '{{ monit.ssl.combined_cert }}'
  when: monit.webinterface.enabled
  tags:
    - webinterface
    - monit
