---
# Part: Backup
#
# Description: Do a rotated backup of the document root on a remote server.
#
# Parameters:
# - rotation: Rotation type (daily, weekly, monthly, yearly)
# - keep_count: How many rotations to keep (eg. 2 will keep two backups in the rotation)
# - docroot: Docroot to backup
# - backup.docroot: Directory where to store backups (on the local machine)
#
# Dependencies:
#
# Creates:
#
# File modifications:
#
###############################################################################

- name: Backup | Check if backup is needed
  script: rotate.sh {{ rotation }} {{ keep_count }} {{ backup.docroot }} {{ docroot|basename }}
  register: do_backup # 0: backup exists, 3: backup required, other: error
  failed_when: do_backup.rc == 3 # Create a backup only when required
  delegate_to: 127.0.0.1 # Run this on localhost

# Try to reuse existing backup from another rotation
###

- name: Backup | Check if backup already exists locally
  shell: find {{ backup.docroot }} -maxdepth 2 -name "{{ docroot|basename }}-{{ ansible_date_time.date }}.tar.gz" -print0 | head -1 | xargs --null realpath
  register: duplicate_path
  delegate_to: 127.0.0.1
  when: do_backup|success

# Backup exists locally but in another rotation directory, reuse it.
- name: Backup | Reuse backup which already exist in different rotation
  command:
    cp {{ duplicate_path }} {{ backup.docroot }}/{{ rotation }}/
    creates={{ backup.docroot }}/{{ rotation }}/{{ docroot|basename }}-{{ ansible_date_time.date }}.tar.gz
  delegate_to: 127.0.0.1
  when: do_backup|success and duplicate_path|success

# Backup needs to be created
# Henceforth only raw and script actions are available
###

- name: Backup | Create temporary filestorage
  raw:
    mkdir /tmp/docroot-dump
    && chmod 700 /tmp/docroot-dump
  when: do_backup|success and duplicate_path|failed

- name: Backup | Archive docroot to /tmp/docroot-dump/{{ docroot|basename }}-{{ ansible_date_time.date }}.tar.gz
  raw:
    tar -czf /tmp/docroot-dump/{{ docroot|basename }}-{{ ansible_date_time.date }}.tar.gz {{ docroot }}
  when: do_backup|success and duplicate_path|failed

- name: Backup | Fetch file back to host
  fetch:
    dest={{ backup.docroot }}/{{ rotation }}/
    flat=yes
    src=/tmp/docroot-dump/{{ docroot|basename }}-{{ ansible_date_time.date }}.tar.gz
  when: exists|failed and duplicate_path|failed

- name: Backup | Clean up temporary files
  raw: rm -rf /tmp/docroot-dump
  when: exists|failed and duplicate_path|failed
