---
# Part: Security
#
# Description: Secures a server
#
# Parameters:
#
# Dependencies:
#
# Creates:
# - /etc/apt/apt.conf.d/10periodic
# - /etc/cron.d/tiger-audit
#
# File modifications:
# - /etc/hosts.conf
# - /etc/fstab
#
###############################################################################

- name: common | Install uttanded-upgrades and dependencies
  apt:
    pkg={{ item }}
    state=present
  with_items:
    - python-software-properties
    - unattended-upgrades
  when: security.common.unattended_upgrades
  tags:
    - security-common
    - security-unattended-upgrades

- name: "common | Adjust APT update intervals: /etc/apt/apt.conf.d/10periodic"
  copy:
    src=apt_periodic
    dest=/etc/apt/apt.conf.d/10periodic
    owner=root group=root
  when: security.common.unattended_upgrades
  tags:
    - unattended-upgrades
    - config

- name: common | Check if su command is overriden
  shell: dpkg-statoverride --list | grep '/bin/su'
  register: su_is_overriden
  ignore_errors: true
  changed_when: false

# @see http://www.thefanclub.co.za/how-to/how-secure-ubuntu-1204-lts-server-part-1-basics
- name: common | Limit su access to only admin group.
  command: dpkg-statoverride --update --add root admin 4750 /bin/su
  when: security.common.limit_su and su_is_overriden|failed
  tags:
    - security-common

# @see http://www.thefanclub.co.za/how-to/how-secure-ubuntu-1204-lts-server-part-1-basics
- name: "common | Prevent IP spoofing: /etc/host.conf"
  lineinfile:
    dest=/etc/host.conf
    regexp="^{{ item.key }}"
    line="{{ item.line }}"
    state=present
  with_items:
    - { key: 'order', line: 'order bind,hosts' }
    - { key: 'nospoof', line: 'nospoof on' }
  when: security.common.ipspoof
  tags:
    - security-common

- name: common | Install tiger security auditing system
  apt:
    pkg=tiger
    state=present
  when: security.common.tiger
  tags:
    - security-common
    - security-tiger

- name: "common | Tiger | Run auditing at 2am on the 1st of every month: /etc/cron.d/tiger-audit"
  cron:
    name="tiger audit"
    cron_file=tiger-audit
    min=0 hour=2 day=1
    job="/usr/sbin/tiger > /dev/null"
    user=root
    state=present
  when: security.common.tiger
  tags:
    - security-common
    - security-tiger

- name: "common | Tiger | Disable cron: /etc/cron.d/tiger-audit"
  cron:
    cron_file=tiger-audit
    state=absent
  when: not security.common.tiger
  tags:
    - security-common
    - security-tiger

# Mount shared memory as wrtiable but without permission to execute programs or
# change UID of running processes.
# @see https://help.ubuntu.com/community/StricterDefaults#Shared_Memory
###
- name: "common | Secure shared memory: /dev/shm"
  mount:
    name=/dev/shm
    fstype=tmpfs
    opts=defaults,noexec,nosuid
    state=present
  notify: reload fstab
  when: security.common.secure_shm
  tags:
    - security-common
