---
# Part: Security
#
# Description: Install denyhosts to block failed ssh login attempts
#
# Parameters:
#
# Dependencies:
#
# Creates:
#
# File modifications:
# - /etc/denyhosts.conf
#
###############################################################################

- name: denyhosts | Install package
  apt:
    pkg=denyhosts
    state=present
  tags:
    - denyhosts
    - install

# @see http://blog.bigdinosaur.org/securing-your-server-with-denyhosts/
- name: "denyhosts | Configure: /etc/denyhosts.conf"
  template:
    src=denyhosts.conf.j2
    dest=/etc/denyhosts.conf
    owner=root group=root
  notify: restart denyhosts
  tags:
    - denyhosts
    - config

# General management
###

- include: ../../common/tasks/service.yml
  vars:
    name: denyhosts
    enabled: '{{ security.denyhosts.enabled }}'

- include: ../../monit/tasks/entry.yml
  vars:
    name: denyhosts
    enabled: '{{ security.denyhosts.enabled }}'


- include: ../../logrotate/tasks/entry.yml
  vars:
    name: denyhosts
    logs: '{{ security.denyhosts.log.file }}'
    special: weekly
    maxage: 30
    enabled: '{{ security.denyhosts.enabled }}'

- include: ../../rsyslog/tasks/entry.yml
  vars:
    name: denyhosts
    mode: programname
    enabled: '{{ security.denyhosts.enabled }}'
    output: '{{ security.denyhosts.log.file }}'
