---
# Part: Security
#
# Description: Enables rootkit detection and manually checks
#
# Parameters:
#
# Dependencies:
#
# Creates:
# - /etc/cron.weekly/rkhunter-cron
#
# File modifications:
#
###############################################################################
- name: rootkit | Install rkhunter package
  apt:
    pkg=rkhunter
    state=present
  tags:
    - security-rootkit

# Only enabled if both enabled and notify_email specified
- name: "rootkit | rkhunter | Run rootkit check at 2am on every sunday: {{ rkhunter_cron }}"
  template:
    src=rkhunter-cron.j2
    dest={{ rkhunter_cron }}
  when: security.rootkit.enabled and security.rootkit.notify_email|bool
  tags:
    - security-rootkit

- name: "rootkit | rkhunter | Disable cron: {{ rkhunter_cron }}"
  file:
    path={{ rkhunter_cron }}
    state=absent
  when: not security.rootkit.enabled or not security.rootkit.notify_email|bool
  tags:
    - security-rootkit
