---
# Part: Security
#
# Description: Secures SSH on the server
# @see https://help.ubuntu.com/community/StricterDefaults#SSH_Settings
#
# Parameters:
#
# Dependencies:
#
# Creates:
#
# File modifications:
# - /etc/ssh/sshd_config
#
###############################################################################

- name: "ssh | Disallow root SSH access: /etc/ssh/sshd_config"
  lineinfile:
    dest=/etc/ssh/sshd_config
    regexp="^PermitRootLogin"
    line="PermitRootLogin no"
    state=present
  when: security.ssh.disallow_root
  notify: restart ssh
  tags:
    - ssh-security
    - security

- name: "ssh | Prevent DoS of SSH daemon: /etc/ssh/sshd_config"
  lineinfile:
    dest=/etc/ssh/sshd_config
    regexp="^LoginGraceTime"
    line="LoginGraceTime 20"
    state=present
  when: security.ssh.prevent_dos
  notify: restart ssh
  tags:
    - ssh-security
    - security

- name: "ssh | Force SFTP: /etc/ssh/sshd_config"
  lineinfile:
    dest=/etc/ssh/sshd_config
    regexp="^Subsystem sftp"
    line="Subsystem sftp internal-sftp"
    state=present
  when: security.ssh.force_sftp
  notify: restart ssh
  tags:
    - ssh-security
    - security

- name: "ssh | Only allow users from admin or sshlogin groups: /etc/ssh/sshd_config"
  lineinfile:
    dest=/etc/ssh/sshd_config
    regexp="^AllowGroups"
    line="AllowGroups {{ security.ssh.access_group }}"
    state=present
  notify: restart ssh
  when: security.ssh.access_group
  tags:
    - ssh-security
    - security
