---
# Part: Security
#
# Description: Configure system to be more secure.
# @see http://www.thefanclub.co.za/how-to/how-secure-ubuntu-1204-lts-server-part-1-basics
#
# Parameters:
#
# Dependencies:
#
# Creates:
#
# File modifications:
#
###############################################################################

- name: sysctl | IP Spoofing protection (enables RFC-reccomended source validation)
  sysctl:
    name={{ item }}
    value=1
    state=present
  with_items:
    - net.ipv4.conf.all.rp_filter
    - net.ipv4.conf.default.rp_filter
  when: security.sysctl.ipspoof
  notify: reload sysctl
  tags:
    - security-sysctl

- name: sysctl | Log suspcicious packets, such as spoofed, source-routed, and redirect
  sysctl:
    name={{ item }}
    value=1
    state=present
  with_items:
    - net.ipv4.conf.all.log_martians
    - net.ipv4.conf.default.log_martians
  when: security.sysctl.log_martians
  notify: reload sysctl
  tags:
    - security-sysctl

- name: sysctl | Protect ICMP attacks
  sysctl:
    name=net.ipv4.icmp_echo_ignore_broadcasts
    value=1
    state=present
  when: security.sysctl.ignore_icmp_broadcasts
  notify: reload sysctl
  tags:
    - security-sysctl

- name: sysctl | Disable source packet routing
  sysctl:
    name={{ item }}
    value=0
    state=present
  with_items:
    - net.ipv4.conf.all.accept_source_route
    - net.ipv6.conf.all.accept_source_route
    - net.ipv4.conf.default.accept_source_route
    - net.ipv6.conf.default.accept_source_route
  when: security.sysctl.disable_source_routing
  notify: reload sysctl
  tags:
    - security-sysctl

- name: sysctl | Make sure no one can alter the routing tables
  sysctl:
    name={{ item }}
    value=0
    state=present
  with_items:
    - net.ipv4.conf.all.send_redirects
    - net.ipv4.conf.default.send_redirects
  when: security.sysctl.ignore_send_redirects
  notify: reload sysctl
  tags:
    - security-sysctl

# http://en.wikipedia.org/wiki/SYN_flood
- name: sysctl | Block SYN attacks
  sysctl:
    name={{ item.name }}
    value={{ item.value }}
    state=present
  with_items:
    - { name: 'net.ipv4.tcp_syncookies', value: 1 }
  when: security.sysctl.synattack
  notify: reload sysctl
  tags:
    - sysctl
    - security

- name: sysctl | 
  sysctl:
    name={{ item }}
    value=0
    state=present
  with_items:
    - net.ipv4.conf.all.accept_redirects
    - net.ipv4.conf.all.secure_redirects
    - net.ipv6.conf.all.accept_redirects
    - net.ipv4.conf.default.accept_redirects
    - net.ipv4.conf.default.secure_redirects
    - net.ipv6.conf.default.accept_redirects
  when: security.sysctl.ignore_icmp_redirects
  notify: reload sysctl
  tags:
    - security-sysctl
