---
# Part: Security
#
# Description: Configure system to be more secure.
# @see http://www.thefanclub.co.za/how-to/how-secure-ubuntu-1204-lts-server-part-1-basics
#
# Parameters:
# - sysctl.ipspoof (default: true)
# - sysctl.ignore_icmp_broadcasts (default: true)
# - sysctl.disable_source_routing (default: true)
# - sysctl.ignore_send_redirects (default: true)
# - sysctl.synattack (default: true)
# - sysctl.ignore_icmp_redirects (default: true)
# - sysctl.ignore_directed_ping (default: true)
#
# Dependencies:
#
# Creates:
#
# File modifications:
#
###############################################################################

- name: sysctl | IP Spoofing protection
  sysctl:
    name={{ item }}
    value=1
    state=present
  with_items:
    - net.ipv4.conf.all.rp_filter
    - net.ipv4.conf.default.rp_filter
  when: sysctl.ipspoof
  tags:
    - sysctl
    - config
    - ipspoofing

- name: sysctl | Ignore ICMP broadcast requests
  sysctl:
    name=net.ipv4.icmp_echo_ignore_broadcasts
    value=1
    state=present
  when: sysctl.ignore_icmp_broadcasts
  tags:
    - sysctl
    - config

- name: sysctl | Disable source packet routing
  sysctl:
    name={{ item }}
    value=0
    state=present
  with_items:
    - net.ipv4.conf.all.accept_source_route
    - net.ipv6.conf.all.accept_source_route
    - net.ipv4.conf.default.accept_source_route
    - net.ipv6.conf.default.accept_source_route
  when: sysctl.disable_source_routing
  tags:
    - sysctl
    - config

- name: sysctl | Ignore send redirects
  sysctl:
    name={{ item }}
    value=0
    state=present
  with_items:
    - net.ipv4.conf.all.send_redirects
    - net.ipv4.conf.default.send_redirects
  when: sysctl.ignore_send_redirects
  tags:
    - sysctl
    - config

# http://en.wikipedia.org/wiki/SYN_flood
- name: sysctl | Block SYN attacks
  sysctl:
    name={{ item[0] }}
    value={{ item[1] }}
    state=present
  with_items:
    - ['net.ipv4.tcp_syncookies', 1]
    - ['net.ipv4.tcp_max_syn_backlog', 2048]
    - ['net.ipv4.tcp_synack_retries', 2]
    - ['net.ipv4.tcp_syn_retries', 5]
  when: sysctl.synattack
  tags:
    - sysctl
    - config

- name: sysctl | Ignore ICMP redirects
  sysctl:
    name={{ item }}
    value=0
    state=present
  with_items:
    - net.ipv4.conf.all.accept_redirects
    - net.ipv6.conf.all.accept_redirects
    - net.ipv4.conf.default.accept_redirects
    - net.ipv6.conf.default.accept_redirects
  when: sysctl.ignore_icmp_redirects
  tags:
    - sysctl
    - config

- name: sysctl | Ignore directed pings
  sysctl:
    name=net.ipv4.icmp_echo_ignore_all
    value=1
    state=present
  when: sysctl.ignore_directed_ping
  tags:
    - sysctl
    - config
