---
# Part: Varnish
#
# Description: Installs and configures Varnish
#
# Parameters:
#
# Dependencies:
# - rsyslog:tasks:add
# - ufw:tasks:entry
#
# Creates:
# - /etc/varnish/drupal.vcl
# - /etc/varnish/error.vcl (does not override!)
#
# File modifications:
# - /etc/default/varnish
# - /etc/varnish/secret
#
###############################################################################

- name: install | Fetch signing key
  apt_key:
    url="http://repo.varnish-cache.org/debian/GPG-key.txt"
    state=present
  when: ansible_lsb.release != "13.04"
  tags:
    - varnish-config

- name: install | Add Varnish repository
  apt_repository:
    repo="deb http://repo.varnish-cache.org/ubuntu/ {{ ansible_lsb.codename }} varnish-3.0"
  when: ansible_lsb.release != "13.04"
  tags:
    - varnish-config

- name: install | Install Varnish package
  apt:
    pkg=varnish
    state=present
  tags:
    - install

- name: config | Count CPU cores
  shell: grep processor /proc/cpuinfo | wc -l
  register: cpu_cores
  changed_when: false
  tags:
    - config

- name: "config | Set varnish startup configurations: /etc/default/varnish"
  template:
    src=varnish.j2
    dest=/etc/default/varnish
    owner=root group=root
  notify: restart varnish
  tags:
    - varnish-config

- name: "security | Verify file permissions: /etc/varnish/secret"
  file:
    path=/etc/varnish/secret
    state=file
    owner=root group=root mode=0600
  tags:
    - varnish-config

- name: "config | Ensure /etc/varnish/custom.vcl exists for error pages and hooks."
  copy:
    src=custom.vcl
    dest=/etc/varnish/custom.vcl
    force=no
    owner=root group=root
  tags:
    - varnish-config

- name: "config | Create default configurations: /etc/varnish/"
  template:
    src={{ item }}.j2
    dest=/etc/varnish/{{ item }}
    owner=root group=root
    validate="varnishd -C -f %s"
  with_items:
    - drupal.vcl
  notify: restart varnish
  tags:
    - varnish-config

# General management
###

- include: ../../common/tasks/service.yml
  vars:
    name: varnish
    enabled: '{{ varnish.enabled }}'
  tags:
    - varnish-config

- include: ../../monit/tasks/entry.yml
  vars:
    name: varnish
    port: '{{ varnish.port }}'
    enabled: '{{ varnish.enabled }}'
  tags:
    - varnish-config

# Manage logrotation
- include: ../../logrotate/tasks/entry.yml
  vars:
    name: varnish
    size: 100M
    maxage: 30
    logs: '{{ varnish.log.file }}'
    enabled: '{{ varnish.log.enabled and varnish.enabled }}'
  tags:
    - varnish-config

- include: ../../rsyslog/tasks/entry.yml
  vars:
    mode: facility
    name: varnish
    facility: '{{ varnish.log.facility }}.*'
    output: '{{ varnish.log.file }}'
    enabled: '{{ varnish.log.enabled and varnish.enabled }}'
  tags:
    - varnish-config

- include: ../../ufw/tasks/entry.yml
  vars:
    name: '{{ varnish.port }}'
    enabled: '{{ varnish.enabled }}'
  tags:
    - varnish-config
