---

mariadb_users:
  active: []
  departed: []

# main.yml
###
mariadb:
  enabled: true

  log:
    file: '/var/log/mysql.err'

  # Should ansible manage root
  manage_root: true

  # Changes if logging is enabled
  development: false

  # Hosts to add users to
  hosts: ['localhost']

  # my.cnf
  ###

  config:
    port: 3306
    socket: /var/run/mysqld/mysqld.sock
    pid_file: /var/run/mysqld/mysqld.pid
    datadir: /var/lib/mysql
    tmpdir: /tmp
    basedir: /usr

    # password: Set this securely

    # MyISAM
    key_buffer_size: 32M

    # Safety
    max_allowed_packet: 16M

    # Caches and limits
    tmp_table_size: 32M
    max_heap_table_size: 32M
    query_cache_type: 1
    query_cache_size: 4M
    query_cache_limit: 256K
    query_cache_min_res_unit: 1K
    max_connections: 128
    thread_cache_size: 128

    # InnoDB
    innodb_buffer_pool_size: 512M
    innodb_flush_log_at_trx_commit: 0

    # Logging
    long_query_time: true
    slow_query_log: true
    slow_query_log_file: /var/log/mysql/mysql-slow.log

    # Buffers
    join_buffer_size: 8M
    read_buffer_size: 2M
    sort_buffer_size: 3M
    read_rnd_buffer_size: 4M

  # PHPMyAdmin
  ###

  pma:
    enabled: true
    install: true
    version: 4.0.9
    local_only: true
