---
# Part: MariaDB
#
# Description: Creates a set of MariaDB users with randomly generated passwords.
#
# Parameters:
# - users: List of account dictionaries, each with the keys:
#   username and privileges
# - login_user (default: root)
#
# Dependencies:
# - tasks:main
#
# Creates:
#
# File modifications:
#
###############################################################################

- name: service | Start the service
  service:
    name=mysql
    state=started
  tags:
    - mariadb-user-create

- name: user | Create users
  mysql_user:
    login_user={{ login_user|default('root') }}
    login_password={{ lookup('password', inventory_dir + '/credentials/' + ansible_hostname + '/' + login_user|default('root') + '/mariadb_password length=15') }}
    name={{ item.username }}
    password={{ lookup('password', inventory_dir + '/credentials/' + ansible_hostname + '/' + item.username + '/mariadb_password length=15') }}
    priv={{ item.privileges }}
    state=present
  when: password is not defined
  with_items: users
  tags:
    - mariadb-user-create
