---
# Part: MariaDB
#
# Description: Creates a set of MariaDB databases
#
# Parameters:
# - databases: List of db dictionaries, each with the keys:
#   - name
# - login_user (default: root)
#
# Dependencies:
# - tasks:main
#
# Creates:
#
# File modifications:
#
###############################################################################

- name: service | Start the service
  service:
    name=mysql
    state=started
  tags:
    - mariadb-db-create

- name: database | Create database
  mysql_db:
    login_user={{ login_user|default('root') }}
    login_password={{ lookup('password', inventory_dir + '/credentials/' + ansible_hostname + '/' + login_user|default('root') + '/mariadb_password length=15') }}
    name={{ item.name }}
    state=present
  with_items: databases
  tags:
    - mariadb-db-create
