---
# Part: MariaDB
#
# Description: Deletes MariaDB users set as absent
#
# Parameters:
# - users: List of account dictionaries, each with the keys: username
# - user: User to log in with (default: root)
# - password: Login password as plain text (optional and not
#   recommended). By default a password lookup will be done.
#
# Dependencies:
# - tasks:main
#
# Creates:
#
# File modifications:
#
###############################################################################

- name: service | Start the service
  service:
    name=mysql
    state=started
  tags:
    - service

# Remove each user. Use a plain text password for remote login (not recommended)
- name: user | Delete users
  mysql_user:
    login_user={{ user|default('root') }}
    login_password={{ password }}
    name={{ item.username }}
    state=absent
  when: password is defined
  with_items: users
  tags:
    - disable
    - user

- name: user | Delete users
  mysql_user:
    login_user={{ user|default('root') }}
    login_password="{{ lookup('password', inventory_dir + '/credentials/' + ansible_hostname + '/' + user|default('root') + '/mariadb_password length=15') }}"
    name={{ item.username }}
    state=absent
  when: password is not defined
  with_items: users
  tags:
    - disable
    - user
