---
# Part: MariaDB
#
# Description: Deletes MariaDB users set as absent
#
# Parameters:
# - users: List of account dictionaries, each with the keys: username
# - login_user: User to log in with (default: root)
#
# Dependencies:
# - tasks:main
#
# Creates:
#
# File modifications:
#
###############################################################################

- name: service | Start the service
  service:
    name=mysql
    state=started
  tags:
    - mariadb-user-delete

- name: user | Delete users
  mysql_user:
    login_user={{ login_user|default('root') }}
    login_password="{{ lookup('password', inventory_dir + '/credentials/' + ansible_hostname + '/' + login_user|default('root') + '/mariadb_password length=15') }}"
    name={{ item.username }}
    state=absent
  with_items: users
  tags:
    - mariadb-user-delete
