---
# Part: MariaDB
#
# Description: Installs and configures MariaDB securely. Manage preconfigured
# users as well.
#
# Parameters:
#
# Dependencies:
# - rsyslog:tasks:entry
# - logrotate:tasks:entry
# - monit:tasks:entry
# - common:tasks:service
#
# Creates:
#
# File modifications:
# - /etc/my.cnf
#
###############################################################################

- name: install | Install ansible dependencies
  apt:
    pkg={{ item }}
    cache_valid_time=3600
    update_cache=yes
    state=present
  with_items:
    - python-mysqldb
    - python-pycurl
    - python-software-properties
  tags:
    - install

- name: install | Add apt key
  apt_key:
    url={{ mariadb_apt_key }}
  tags:
    - install

- name: install | Add repository
  apt_repository:
    repo="deb http://download.nus.edu.sg/mirror/mariadb/repo/5.5/ubuntu precise main"
  tags:
    - install

- name: install | Install required packages
  apt:
    pkg={{ item }}
    state=present
  with_items:
    - mariadb-server
    - mariadb-client
  tags:
    - install

- name: "config | Configure: /etc/mysql/my.cnf"
  template:
    src=my.cnf.j2
    dest=/etc/mysql/my.cnf
    owner=root group=root mode=0600
  notify: restart mariadb
  tags:
    - config

# Start service now as we need it to configure root
- name: service | Start mysql service
  service:
    name=mysql
    state=started
  tags:
    - service
    - enable

- name: config | Check if root password is generated
  sudo: false
  local_action: raw test -s {{ inventory_dir }}/credentials/{{ ansible_hostname }}/root/mariadb_password
  changed_when: false
  ignore_errors: true
  register: root_password_set
  tags:
    - config

- name: config | Set root password (first time)
  mysql_user:
    name=root
    password={{ lookup('password', inventory_dir + '/credentials/' + ansible_hostname + '/root/mariadb_password length=15') }}
    priv="*.*:ALL,GRANT"
    state=present
  when: mariadb.manage_root and root_password_set|failed
  tags:
    - config

# Subsequent run requires the login information.
- name: config | Set root password (verify)
  mysql_user:
    login_user=root
    login_password={{ lookup('password', inventory_dir + '/credentials/' + ansible_hostname + '/root/mariadb_password length=15') }}
    name=root
    password={{ lookup('password', inventory_dir + '/credentials/' + ansible_hostname + '/root/mariadb_password length=15') }}
    priv="*.*:ALL,GRANT"
    state=present
  when: mariadb.manage_root and root_password_set|success
  tags:
    - config

- include: create-users.yml
  vars:
    users: mariadb_users.active
  when: mariadb_users.active|default(false)|bool

- include: delete-users.yml
  vars:
    users: mariadb_users.departed
  when: mariadb_users.departed|default(false)|bool

- include: phpmyadmin.yml
  when: mariadb.pma.install

# General management

- include: ../../common/tasks/service.yml
  vars:
    name: mysql
    enabled: '{{ mariadb.enabled }}'

- include: ../../monit/tasks/entry.yml
  vars:
    name: mysql
    port: '{{ mariadb.config.port }}'
    enabled: '{{ mariadb.enabled }}'

- include: ../../rsyslog/tasks/entry.yml
  vars:
    name: mysql-log
    mode: filemonitor
    logfile: '{{ mariadb.log.file }}'
    enabled: '{{ mariadb.enabled }}'

- include: ../../rsyslog/tasks/entry.yml
  vars:
    name: mysql-slow-query
    mode: filemonitor
    logfile: '{{ mariadb.config.slow_query_log_file }}'
    enabled: '{{ mariadb.enabled }}'
