---
# Part: MariaDB
#
# Description: Installs and configures MariaDB securely. Manage preconfigured
# users as well.
#
# Parameters:
# - development: Whether to use development or production configurations in
#   my.cnf (default: false).
# - configure_root (default: true).
# - enabled (default: true)
# - active: List of active users
# - departed: List of departed users
# - hosts: List of hosts (default: ['localhost'])
#
# - login.user (default: root)
# - login.password (default: false)
# - login.password_file (default: credentials/{{ hostname }}/root/mariadb_password length=15)
#
# Dependencies:
#
# Creates:
#
# File modifications:
# - /etc/my.cnf
#
###############################################################################

- name: MariaDB | Install required packages
  apt:
    pkg={{ item }}
    state=present
  with_items:
    - mariadb-server
    - mariadb-client
  tags:
    - install

- name: MariaDB | Configure: /etc/my.cnf
  template:
    src=my.cnf.j2
    dest=/etc/my.cnf
    mode=0600
  notify: restart mariadb
  tags:
    - config

# Start service now as we need it to configure root, this also sets the service
# to autostart but this will be disabled at the end of the play if configured
# thusly.
- name: MariaDB | Start service and enable on startup
  service:
    name=mysqld
    state=started
    enabled=true
  tags:
    - service
    - enable

- name: MariaDB | Set root password for all hosts
  mysql_user:
    # Dont provide login user, first time root user is without password.
    name=root
    host={{ item }}
    # Password is stored in plain text at credentials/root/mariadb_password
    password={{ lookup('password', 'credentials/' + hostname + '/root/mariadb_password length=15') }}
    priv=*.*:ALL,GRANT # Only root should have GRANT
    state=present
  when: configure_root
  with_items:
    - {{ hostname }}
    - 127.0.0.1
    - ::1
    - localhost
  tags:

- include: create-users.yml
  vars:
    accounts: active

- include: delete-users.yml
  vars:
    users: departed
  tags:
    - clean

- name: MariaDB | Shutdown service and disable autostart.
  service:
    name=mysqld
    state=stopped
    enabled=false
  when: not enabled
  tags:
    - service
    - disable

- include: phpmyadmin.yml
  when: pma.install
