---
# Part: MariaDB
#
# Description: Installs PHPMyAdmin and adds it to the localhost only apache
# virtual host
#
# Parameters:
#
# Dependencies:
# - apache:tasks:main
# - apache:tasks:vhost-local-alias
#
# Creates:
# - /opt/phpmyadmin
# - {{ vhost_local.url }}/pma: Localhost only access to phpmyadmin
#
# File modifications:
# - /etc/phpmyadmin/config.inc.php
#
###############################################################################
- name: pma | Install dependencies
  apt:
    pkg={{ item }}
    state=present
  with_items:
    - php5-mcrypt
  tags:
    - phpmyadmin
    - install

- include: ../../common/tasks/source-install.yml
  vars:
    tarball: '{{ pma_install.tarball }}'
    sha256sum: '{{ pma_install.sha256sum }}'
    strip: 1
    name: phpmyadmin
    destination: /opt
    creates: index.php
    update: false

# Manage local vhost alias /pma
- include: ../../apache/tasks/vhost-local-alias.yml
  vars:
    docroot: /opt/phpmyadmin
    alias: /pma
    enabled: '{{ mariadb.pma.enabled }}'

# Used in /etc/phpmyadmin/config.inc.php
- name: pma | Generate random blowfish secret
  shell: openssl passwd -1 -in /dev/urandom | head -1 | cut -c 20-
  register: pma_blowfish_secret
  changed_when: false
  tags:
    - phpmyadmin
    - config

# This will continuasly trigger change event as secret changes.
- name: "pma | Create: /etc/phpmyadmin"
  file:
    path=/etc/phpmyadmin
    state=directory
  tags:
    - phpmyadmin
    - config

- name: "pma | Configure: /etc/phpmyadmin/config.inc.php"
  template:
    src=phpmyadmin/config.inc.php.j2
    dest=/etc/phpmyadmin/config.inc.php
    owner=root group=root
  tags:
    - phpmyadmin
    - config

- name: "pma | Update blowfish secret: /etc/phpmyadmin/secret.inc.php"
  template:
    src=phpmyadmin/secret.inc.php.j2
    dest=/etc/phpmyadmin/secret.inc.php
    owner=root group=root
  changed_when: false
  tags:
    - phpmyadmin
    - config
