---
# Job: Install Dotfiles
#
# Description: Installs dotfiles for a specified user account
#
# Parameters:
# - user: Username of user where to install dotfiles
#
# Dependencies:
#
# Creates:
# - /home/{{ username }}/.dotfiles
# - /home/{{ username }}/.*
#
# File modifications:
#
###############################################################################

- hosts: any
  user: root
  vars:
    dotfils_repository: https://github.com/generoi/dotfiles
  tasks:
    - name: User | Make sure user {{ user }} exists
      command: id -u {{ user }}
      register: user_exists

    - name: User | Get dotfiles for user: /home/{{ user }}/.dotfiles
      git:
        repo={{ dotfiles_repository }}
        dest=/home/{{ user }}/.dotfiles
      when: user_exists|success

    - name: User | Install dotfiles
      command:
        /home/{{ user }}/.dotfiles/bootstrap.sh install
        creates=/home/{{ user }}/.vimrc
      when: user_exists|success

    - name: User | Change owner of all files: /home/{{ user }}
      file:
        path=/home/{{ user }}/
        owner={{ user }} group={{ user }}
      when: user_exists|success
