---
# Job: Install Dotfiles
#
# Description: Installs dotfiles for a specified user account
#
# Parameters:
# - user: Username of user where to install dotfiles
#
# Dependencies:
#
# Creates:
# - /home/{{ username }}/.dotfiles
# - /home/{{ username }}/.*
#
# File modifications:
#
###############################################################################

- hosts: any
  #user: root
  vars:
