---
newrelic_license: false

newrelic:
  sysmond:
    enabled: true
    install: true
    loglevel: 'info'
    logfile: '/var/log/newrelic/nrsysmond.log'

  php:
    enabled: true
    install: true
    loglevel: 'info'
    logfile: '/var/log/newrelic/php_agent.log'
    daemon_logfile: '/var/log/newrelic/newrelic-daemon.log'
    daemon_loglevel: 'info'

    browser_monitoring_auto_instrument: true
    drupal_modules: true
    error_collector:
      record_database_errors: true
      include_notices: true
    analytics_events: true
