---
# Part: New Relic
#
# Description: Sets up New Relic
#
# Parameters:
#
# Dependencies:
#
# Creates:
# - group: newrelic
#
# File modifications:
#
###############################################################################

- name: install | Add New Relic key
  apt_key:
    url={{ newrelic_apt_key }}
    state=present
  tags:
    - install

- name: install | Add New Relic repository
  apt_repository:
    repo="{{ newrelic_repository }}"
  tags:
    - install

- name: config | Create newrelic group newrelic
  group:
    name=newrelic
    state=present
  tags:
    - config
    - acl

- include: php.yml
  when: newrelic.php.install

- include: sysmond.yml
  when: newrelic.sysmond.install
