---
# Part: New Relic
#
# Description: Sets up New Relic
#
# Parameters:
# - php.install: Enable the php agent (default: true).
# - sysmond.install: Install the php agent (default: true).
# - php.*: See php.yml
# - sysmond.*: See symond.yml
# - license_key: The license key used
#
# Dependencies:
#
# Creates:
# - group: newrelic
#
# File modifications:
#
###############################################################################

- name: New Relic | Add New Relic key:https://download.newrelic.com/548C16BF.gpg
  apt_key:
    url=https://download.newrelic.com/548C16BF.gpg
    state=present
  tags:
    - install

- name: New Relic | Add New Relic repository
  apt_repository:
    repo="http://apt.newrelic.com/debian/ newrelic non-free"
  tags:
    - install

- name: New Relic | Create newrelic group: newrelic
  group:
    name=newrelic
    state=present
  tags:
    - config
    - acl

- include: php.yml
  when: php.install

- include: sysmond.yml
  when: sysmond.install
