---
# Part: New Relic
#
# Description: Sets up the PHP agent for New Relic
#
# Parameters:
#
# Dependencies:
# - tasks:main
#
# Creates:
# - /etc/newrelic/newrelic.cfg
#
# File modifications:
#
###############################################################################

- name: php | Install agent
  apt:
    pkg=newrelic-php5
    state=present
  tags:
    - newrelic-php

- name: "php | Configure: /etc/php5/conf.d/newrelic.ini"
  template:
    src=newrelic.ini.j2
    dest=/etc/php5/conf.d/newrelic.ini
    owner=root group=newrelic
  notify: restart apache
  tags:
    - newrelic-php

# General management
###

# @TODO monit?

- include: ../../logrotate/tasks/entry.yml
  vars:
    name: newrelic
    size: 10M
    special: weekly
    maxage: 30
    logs: '{{ newrelic.php.logfile }} {{ newrelic.php.daemon_logfile }}'
    enabled: '{{ newrelic.php.enabled }}'
  tags:
    - newrelic-php

- include: ../../rsyslog/tasks/entry.yml
  vars:
    name: newrelic-php-agent
    mode: filemonitor
    logfile: '{{ newrelic.php.logfile }}'
    enabled: '{{ newrelic.php.enabled }}'
  tags:
    - newrelic-php

- include: ../../rsyslog/tasks/entry.yml
  vars:
    name: newrelic-php-daemon
    mode: filemonitor
    logfile: '{{ newrelic.php.daemon_logfile }}'
    enabled: '{{ newrelic.php.enabled }}'
  tags:
    - newrelic-php
