---
# Part: New Relic
#
# Description: Sets up the system monitor agent for New Relic
#
# Parameters:
#
# Dependencies:
# - tasks:main
#
# Creates:
# - /etc/newrelic/nrsysmond.cfg
#
# File modifications:
#
###############################################################################

- name: sysmond | Install agent
  apt:
    pkg=newrelic-sysmond
    state=present
  tags:
    - newrelic-sysmond

- name: "sysmond | Configure: /etc/newrelic/nrsysmond.cfg"
  template:
    src=nrsysmond.cfg.j2
    dest=/etc/newrelic/nrsysmond.cfg
    owner=root group=newrelic mode=0640
  notify: restart newrelic-sysmond
  tags:
    - newrelic-sysmond

# General management
###

- include: ../../common/tasks/service.yml
  vars:
    name: newrelic-sysmond
    enabled: '{{ newrelic.sysmond.enabled and newrelic_license|default(false) }}'
  tags:
    - newrelic-sysmond

- include: ../../monit/tasks/entry.yml
  vars:
    name: newrelic-sysmond
    enabled: '{{ newrelic.sysmond.enabled }}'
  tags:
    - newrelic-sysmond

- include: ../../logrotate/tasks/entry.yml
  vars:
    name: newrelic-sysmond
    special: weekly
    logs: '{{ newrelic.sysmond.logfile }}'
    enabled: '{{ newrelic.sysmond.enabled }}'
  tags:
    - newrelic-sysmond

- include: ../../rsyslog/tasks/entry.yml
  vars:
    name: newrelic-sysmond
    mode: filemonitor
    logfile: '{{ newrelic.sysmond.logfile }}'
    enabled: '{{ newrelic.sysmond.enabled }}'
  tags:
    - newrelic-sysmond
