---
# Part: Development
#
# Description: Install common packages used for development servers
#
# Parameters:
#
# Dependencies:
#
# Creates:
#
# File modifications:
#
###############################################################################

- include: common.yml

- include: vim.yml
  when: development.vim.install

- include: afp.yml
  when: development.afp.install

- include: ruby.yml
  vars:
    packages: '{{ development.ruby.gems }}'
    global: true
  when: development.ruby.install

- include: nodejs.yml
  vars:
    packages: '{{ development.nodejs.packages }}'
    global: true
  when: development.nodejs.install
