---
# Part: Development
#
# Description: Install NPM packages
#
# Parameters:
# - packages: List of packages to install
# - global (default: false)
# - path: If not global, the path should be set
#
# Dependencies:
#
# Creates:
#
# File modifications:
#
###############################################################################

- name: node.js | install | Install ansible dependencies
  apt:
    pkg={{ item }}
    cache_valid_time=3600
    update_cache=yes
    state=present
  with_items:
    - python-pycurl
  tags:
    - development-nodejs
    - ansible

- name: node.js | install | Add node PPA repository
  apt_repository:
    repo={{ nodejs_repository }}
  tags:
    - development-nodejs

- name: node.js | install | Install required packages
  apt:
    pkg=nodejs
    state=present
  tags:
    - development-nodejs

- name: node.js | npm | Install npm packages
  npm:
    name={{ item }}
    global=no
    path={{ path }}
    state=present
  with_items: packages
  when: not global|default(false)
  tags:
    - development-nodejs
    - development-nodejs-npm

- name: node.js | npm | Install npm packages globally
  npm:
    name={{ item }}
    global=yes
    state=present
  with_items: packages
  when: global|default(false)
  tags:
    - development-nodejs
    - development-nodejs-npm
