---
# Part: Development
#
# Description: Install rubygems.
#
# Parameters:
# - packages: List of gems to install.
#
# Dependencies:
#
# Creates:
#
# File modifications:
#
###############################################################################

- name: ruby | install | Install required ruby packages.
  apt:
    pkg={{ item }}
    state=present
  with_items:
    - ruby
    - rubygems
  tags:
    - development-ruby

- name: ruby | gem | Install ruby gems
  gem:
    name={{ item }}
    state=latest
  with_items: packages
  tags:
    - development-ruby
    - development-ruby-gems
