---
pound:
  enabled: true

  ssl:
    certificate: /etc/ssl/certs/ssl-cert-snakeoil.pem
    private_key: /etc/ssl/private/ssl-cert-snakeoil.key
    combined_cert: /etc/ssl/combined/ssl-cert-snakeoil.pem

  # Whether to join $pound_certificate and $pound_private_key into the finald $pound_key
  join_cert_key: true

  user: www-data
  group: www-data

  alive_check: 30
  port: 443
  ip: '{{ ip }}'

  # Should be set to varnish
  backend:
    addr: 127.0.0.1
    port: 80

  log:
    level: 3
    facility: local6 # @see http://en.wikipedia.org/wiki/Syslog
    file: /var/log/pound.log
