---
# Part: Mail
#
# Description: Setup a local and null mailclient which only sends email.
#
# @TODO should support other mail systems
#
# Parameters:
# - enabled (default: true)
#
# Dependencies:
#
# Creates:
#
# File modifications:
#
###############################################################################

- include: postfix.yml
