---
# Part: Mail
#
# Description: Setup a local and null postfix client
#
# Parameters:
# - enabled (default: true)
#
# Dependencies:
#
# Creates:
#
# File modifications:
# - /etc/postfix/main.cf
#
###############################################################################

- name: Postfix | Copy debconf selections so that Postfix can configure itself non-interactively
  template:
    src=postfix_selections
    dest=/tmp/postfix_selections
    mode=0600
  tags:
    - config
    - postfix

- name: Postfix | Set up Postfix to handle mail directly using SMTP
  command: debconf-set-selections /tmp/postfix_selections
  tags:
    - config
    - postfix

- name: Postfix | Install required packages
  apt:
    pkg={{ item }}
    state=present
  with_items:
    - postfix
    - mailutils
    - ca-certificates
  tags:
    - install
    - postfix

- name: Postfix | Set up Postfix to be a null client, only sending mail: /etc/postfix/main.cf
  template:
    src=postfix-main.cf.j2
    dest=/etc/postfix/main.cf
  notify: reload postfix
  tags:
    - config
    - postfix

- name: Postfix | Enable service and autostart it on boot
  service:
    name=postfix
    state=running
    enabled=yes
  when: enabled
  tags:
    - service
    - postfix
    - enable

- name: Postfix | Shutdown service and disable autostart
  service:
    name=postfix
    state=stopped
    enabled=no
  when: enabled
  tags:
    - service
    - postfix
    - disable
