---
monit:
  enabled: true

  config:
    daemon: 120
    daemon_delay: 120

  log:
    file: '/var/log/monit.log'
    facility: local5

  # Webinterface settings
  webinterface:
    install: true
    enabled: true
    port: 2812
    addr: localhost
    rw_group: sudo
    r_group: admin

  ssl:
    certificate: /etc/ssl/certs/ssl-cert-snakeoil.pem
    private_key: /etc/ssl/private/ssl-cert-snakeoil.key
    combined_cert: /etc/ssl/combined/monit.pem

  # Email notifications
  mail:
    install: false
    enabled: false
    alerts: '{{ notify_email }}'
    timeouts: '{{ notify_email }}'
