---
enabled: true

mysql:
  port: 3306

apache:
  port: 80

varnish:
  port: 6081

pound:
  port: 443

# Services to monitor
services: []

# Webinterface settings
webinterface:
  install: false
  enabled: false
  port: 2812
  bind: 0.0.0.0
  rw_group: sudo
  r_group: admin

# Email notifications
mail:
  install: false
  enabled: false
  alerts: []
  timeouts: []
