---
# Part: Common
#
# Description: Install common packages used for every server
#
# Parameters:
#
# Dependencies:
# - ufw:tasks:entry
# - tasks:service
#
# Creates:
# - /etc/update-mord.d/95-ansible
#
# File modifications:
# - /home/{{ ansible_ssh_user }}/.ssh/known_hosts
# - /etc/hosts.allow
#
###############################################################################

- name: update | Update APT package list cache
  apt:
    update-cache=yes
    cache_valid_time=3600
  tags:
    - common-config

- name: update | Upgrade APT packages
  apt:
    upgrade=yes
  tags:
    - common-config

- name: install | Ansible dependencies
  apt:
    pkg={{ item }}
    state=present
  with_items:
    - python-pycurl
  tags:
    - common-config
    - ansible

- name: install | Add git repository for version 1.8
  apt_repository:
    repo="ppa:git-core/ppa"
    state=present
  tags:
    - common-config
    - common-git

- name: install | Common packages for every environment
  apt:
    pkg={{ item }}
    state=present
  with_items: common.packages
  tags:
    - common-config

- include: terminfo.yml

- name: "motd | enable | MOTD explaining server is under Ansible control: /etc/update-motd.d/95-ansible"
  template:
    src=motd
    dest=/etc/update-motd.d/95-ansible
    mode=0755
  when: common.motd.enabled
  tags:
    - common-config

- name: "motd | disable | Disable MOTD: /etc/update-motd.d/95-ansible"
  file:
    path=/etc/update-motd.d/95-ansible
    state=absent
  when: not common.motd.enabled
  tags:
    - common-config

- name: "config | known hosts | Add known hosts: /home/{{ ansible_ssh_user }}/.ssh/known_hosts"
  lineinfile:
    dest=/home/{{ ansible_ssh_user }}/.ssh/known_hosts
    regexp="^{{ item.host }}"
    line="{{ item.line }}"
    state=present
  with_items: common.known_hosts.hosts
  when: common.known_hosts.enabled
  tags:
    - common-config

- name: "config | hosts | Prevent hosts from being locked out of ssh: /etc/hosts.allow"
  lineinfile:
    dest=/etc/hosts.allow
    regexp="^sshd{{':'}} {{ item }}"
    line="sshd{{':'}} {{ item }}"
    state=present
  with_items: common.hosts_allow
  tags:
    - common-config

- name: "config | ufw | Prevent hosts from being blocked by ufw"
  command: ufw allow from {{ item }}
  with_items: common.hosts_allow
  register: result
  changed_when: "'Skipping' not in result.stdout"
  tags:
    - common-config

- name: "config | ipv6 | Disable IPv6"
  command: ufw allow from {{ item }}
  with_items: common.hosts_allow
  register: result
  changed_when: "'Skipping' not in result.stdout"
  tags:
    - common-config
    - common-ipv6

- name: config | ipv6 | Disable IPv6
  sysctl:
    name={{ item }}
    value=1
    state=present
  with_items:
    - net.ipv6.conf.all.disable_ipv6
    - net.ipv6.conf.default.disable_ipv6
    - net.ipv6.conf.lo.disable_ipv6
  # OpenVZ does not have the kernel features required for ipv6
  when: ansible_virtualization_type == 'openvz' or not common.ipv6.enable
  notify: reload sysctl
  tags:
    - common-config
    - common-ipv6

- name: config | ipv6 | Enable IPv6
  sysctl:
    name={{ item }}
    value=0
    state=present
  with_items:
    - net.ipv6.conf.all.disable_ipv6
    - net.ipv6.conf.default.disable_ipv6
    - net.ipv6.conf.lo.disable_ipv6
  when: not ansible_virtualization_type == 'openvz' and common.ipv6.enable
  notify: reload sysctl
  tags:
    - common-config
    - common-ipv6

# General management for NTP
###

- include: service.yml
  vars:
    name: ntp
  tags:
    - common-config
    - common-ntp

- include: ../../ufw/tasks/entry.yml
  vars:
    name: '123/udp'
  tags:
    - common-config
    - common-ntp
