---
# Part: Common
#
# Description: Downloads and extract a package from a remote tarball
#
# Parameters:
# - name
# - tarball
# - sha256sum
# - creates
# - destination (default: /opt)
# - update (default: false)
#
# Dependencies:
#
# Creates:
# - {{ destination }}/{{ name }}
#
# File modifications:
#
###############################################################################

- name: "source | install | Check if package already exists in: {{ destination|default('/opt') }}/{{ name }}/{{ creates }}"
  file:
    path={{ destination|default('/opt') }}/{{ name }}/{{ creates }}
    state=file
  register: package_exists
  ignore_errors: true
  changed_when: false

- name: "source | clean | Clean old files"
  file:
    path={{ destination|default('/opt') }}/{{ name }}
    state=absent
  when: package_exists|success and update|default(false)

- name: "souce | install | Download source to: /tmp/{{ tarball|basename }}"
  get_url:
    url={{ tarball }}
    sha256sum={{ sha256sum }}
    dest=/tmp/{{ tarball|basename }}
    mode=0440
  when: package_exists|failed or update|default(false)

- name: "source | install | Create: {{ destination|default('/opt') }}/{{ name }}"
  file:
    path={{ destination|default('/opt') }}/{{ name }}
    state=directory
  when: package_exists|failed or update|default(false)

- name: "source | install | Extract source: {{ destination|default('/opt') }}/{{ name }}"
  command:
    tar -xf /tmp/{{ tarball|basename }} --strip {{ strip|default(0) }} -C {{ destination|default('/opt') }}/{{ name }}
    creates={{ destination|default('/opt') }}/{{ name }}/{{ creates }}
  when: package_exists|failed or update|default(false)

- name: "source | clean | Clean up temporary files"
  file:
    path=/tmp/{{ tarball|basename }}
    state=absent
