# deflate expires headers mime setenvif substitute
enabled: true
mods_enabled: ['rewrite', 'vhost_alias', 'ssl']
mods_disabled: []
root: /var/www

user: www-data
group: www-data
admin: admin@localhost

port:
  http: 80
  https: 443

config:
  timeout: 300
  keepalive:
    enabled: 'On'
    keepalive_requests: '100'
    keepalive_timeout: '2'

  mpm.mpm_start_servers:       2
  mpm.min_spare_threads:      25
  mpm.spare_threads:          25
  mpm.max_spare_threads:      75
  mpm.thread_limit:           64
  mpm.threads_per_child:      25
  mpm.max_clients:           150
  mpm.max_requests_per_child:  0

# Create virtual hosts
###

# Disable listing of directory content and searching for files on
# incorrect filenames
docroot_options: '-Indexes -MultiViews'
create_docroot: true
remove_docroot: false
local_only: false
ssl:
  enabled: false
  only: false
  certificate_file: false
  certificate_key_file: false
  certificate_chain_file: false
  options: '+FakeBasicAuth +StrictRequire'
vhost_server_alias: false
vhost_include: []

# Default snakeoil certificate from ssl-cert package.
snakeoil:
  certificate: /etc/ssl/certs/ssl-cert-snakeoil.pem
  key: /etc/ssl/private/ssl-cert-snakeoil.key
