---
apache:
  # main.yml
  ###

  enabled: true
  mods_enabled: ['rewrite', 'vhost_alias', 'ssl', 'deflate', 'expires', 'headers', 'mime']
  mods_disabled: []

  # Global values used across other roles.
  ###

  user: www-data
  group: www-data
  admin: admin@localhost

  log:
    error_file: '/var/log/apache2/error.log'
    access_file: '/var/log/apache2/access.log'

  port:
    http: 80
    https: 443

  # Setup wildcard subdomains.
  wildcard_subdomains: true

  # apache2.conf
  ###

  config:
    timeout: 300
    keepalive:
      enabled: On
      requests: 100
      timeout: 2

    mpm:
      mpm_start_servers:       2
      min_spare_threads:      25
      spare_threads:          25
      max_spare_threads:      75
      thread_limit:           64
      threads_per_child:      25
      max_clients:           150
      max_requests_per_child:  0

  # Used for creating the default virtual host of the server.
  ###

  ssl:
    enabled: true
    certificate_file: '{{ snakeoil.certificate }}'
    certificate_key_file: '{{ snakeoil.key }}'
    certificate_chain_file: false
