---
# Part: PHP
#
# Description: Install APC from PECL and configure it.
#
# Parameters:
#
# Dependencies:
# - tasks:setup
# - tasks:pecl: Used to install PECL packages
# - apache:tasks:main: Apache should be installed.
# - apache:tasks:vhost-local-alias: Manage localhost only accessable vhost alias
#
# Creates:
# - /opt/apc: Frontend for apc
# - {{ vhost_local.url }}/apc: Localhost only access to apc
#
# File modifications:
# - /etc/php5/conf.d/apc.ini
#
###############################################################################

- include: pecl.yml
  vars:
    package: apc
    version: beta

- name: apc | Create APC frontend directory
  file:
    path=/opt/apc
    state=directory
  tags:
    - apc
    - config

- name: "apc | Set up frontend web ui: /opt/apc/index.php"
  command:
    cp {{ php.apc.frontend_archive }} /opt/apc/index.php
    creates=/opt/apc/index.php
  tags:
    - apc
    - config

- name: apc | Disable authentication for frontend
  lineinfile:
    dest=/opt/apc/index.php
    regexp="^defaults\('USE_AUTHENTICATION'"
    line="defaults('USE_AUTHENTICATION', 0);"
  tags:
    - apc
    - config

# Manage local access only vhost alias /apc
- include: ../../apache/tasks/vhost-local-alias.yml
  vars:
    docroot: /opt/apc
    alias: /apc
    enabled: '{{ php.apc.enabled }}'
