---
# Part: PHP
#
# Description: Install PHP and related packages
#
# Parameters:
#
# Dependencies:
#
# Creates:
#
# File modifications:
#
###############################################################################

- include: setup.yml

- include: apc.yml
  when: php.apc.install

- include: php-dev.yml
  when: php.development
