---
# Part: PHP
#
# Description: Installs PHP PEAR and sets it up for auto-discovery.
#
# Parameters:
#
# Dependencies:
# - tasks:setup
#
# Creates:
#
# File modifications:
#
###############################################################################
- name: PHP | PEAR | Install PHP development packages: php-pear
  apt:
    pkg=php-pear
    state=installed
  tags:
    - install

- name: PHP | PHPDev | Update pear packages
  command: pear upgrade

- name: PHP | Set pear auto-discover
  command: pear config-set auto_discover 1
