---
# Part: PHP
#
# Description: Installs PEAR package
#
# Parameters:
# - package
#
# Dependencies:
# - tasks:setup
#
# Creates:
#
# File modifications:
#
###############################################################################
- name: pear | Install PHP development packages for pear
  apt:
    pkg=php-pear
    state=installed
  tags:
    - install

- name: pear | Update pear packages
  command: pear upgrade
  changed_when: false

- name: pear | Set pear auto-discover
  command: pear config-set auto_discover 1
  changed_when: false

- name: pear | Install package {{ package }}
  command: pear install {{ package }}
  register: pear_output
  failed_when: pear_output.rc != 0 and 'already installed' not in pear_output.stdout
  changed_when: "'already installed' not in pear_output.stdout"
  ignore_errors: true
