---
# Part: PHP
#
# Description: PECL package installation
#
# Parameters:
# - package
# - version: string, beta, alpha
# - stdin
#
# Dependencies:
#
# Creates:
# - /etc/php5/conf.d/{{ package }}.ini
#
# File modifications:
#
###############################################################################

- name: pecl | Ensure PHP development packages are installed
  apt:
    pkg={{ item }}
    state=present
  with_items:
    - php5-dev
    - php-pear
    - make
  tags:
    - php-pecl

- name: "pecl | Test for previous {{ package }} install"
  shell:  pecl list | grep -i '{{ package }}'
  register: php_package_exists
  changed_when: php_package_exists.rc != 0
  ignore_errors: true
  tags:
    - php-pecl

- name: "pecl | Install {{ package }}-{{ version }}"
  shell:
    printf "{{ stdin|default('\n') }}" | pecl install {{ package }}-{{ version }}
  register: result
  when: php_package_exists|failed
  tags:
    - php-pecl

- name: "pecl | Set {{ package }} config"
  template:
    src=conf.d/{{ package }}.ini.j2
    dest=/etc/php5/conf.d/{{ package }}.ini
    owner=root group=root
  notify: restart php
  tags:
    - php-pecl
