---
# Part: PHP
#
# Description: PECL package installation
#
# Parameters:
# - package
# - version: string, beta, alpha
#
# Dependencies:
#
# Creates:
# - /etc/php5/conf.d/{{ package }}.ini
#
# File modifications:
#
###############################################################################
---

- name: PHP | PECL | Ensure PHP development packages are installed: php5-dev, php-pear, make
  apt:
    pkg={{ item }}
    state=present
  with_items:
    - php5-dev
    - php-pear
    - make

- name: PHP | PECL | Test for previous {{ package }} install
  shell:  pecl list | grep -i '{{ package }}'
  register: php_package_exists
  ignore_errors: yes

- name: PHP | PECL | Install {{ package }}-{{ version }}
  command: pecl install {{ package }}-{{ version }}
  when: php_package_exists|failed

- name: PHP | PECL | Set {{ package }} config (Ubuntu == 12.04)
  template:
    src={{ package }}.ini.j2
    dest=/etc/php5/conf.d/{{ package }}.ini
  when: ansible_lsb.release == "12.04"
  notify: restart php

- name: PHP | PECL | Set {{ package }} config (Ubuntu > 12.04)
  template:
    src={{ package }}.ini.j2
    dest=/etc/php5/mods-available/{{ package }}.ini
  when: ansible_lsb.release != "12.04"
  notify: restart php

- name: PHP | PECL | Set symbolic link to {{ package }} config (Ubuntu > 12.04)
  file:
    src=/etc/php5/mods-available/{{ package }}.ini
    dest=/etc/php5/conf.d/20-{{ package }}.ini
    state=link
  when: ansible_lsb.release != "12.04"
  notify: restart php
