---
# Part: PHP
#
# Description: Installs PHP packages used for development, for example
# profiling tools.
#
# Parameters:
#
# Dependencies:
# - tasks:setup
# - tasks:pear
#
# Creates:
# - /usr/local/bin/composer
# - /usr/bin/phpunit
#
# File modifications:
#
###############################################################################

# PHP QA Toolchain
##
- include: pear.yml
  vars:
    package: pear.phpqatools.org/phpqatools
  when: php.phpqatools.install

# Composer
###
- name: composer | Check if composer is installed
  file:
    path={{ php.composer.dir }}/composer
    state=file
  ignore_errors: true
  register: composer_exists

- name: "composer | Download install script: /tmp/composer.php"
  get_url:
    url={{ composer_install.script }}
    dest=/tmp/composer.php
    sha256sum={{ composer_install.sha256sum }}
  when: php.composer.install and composer_exists|failed
  tags:
    - php-dev
    - composer
    - install

- name: "composer | Run install script"
  command:
    php /tmp/composer.php -- --install-dir={{ php.composer.dir }}
    creates={{ php.composer.dir }}/composer.phar
  when: php.composer.install and composer_exists|failed
  tags:
  tags:
    - php-dev
    - composer
    - install
 
- name: "composer | Rename .phar for binary"
  command:
    mv {{ php.composer.dir }}/composer.phar {{ php.composer.dir }}/composer
    creates={{ php.composer.dir }}/composer
    removes={{ php.composer.dir }}/composer.phar
  when: php.composer.install and composer_exists|failed
  tags:
    - php-dev
    - composer
    - install
 
- name: "composer | Remove install script"
  file:
    path=/tmp/composer.php
    state=absent
  tags:
    - php-dev
    - composer
    - install

- include: xhprof.yml
  when: php.xhprof.install

- include: xdebug.yml
  when: php.xdebug.install
