---
# Part: PHP
#
# Description: Installs PHP 5.4 (specific for Ubuntu 12.04) with useful
# packages and configures php.ini for development/production
#
# Parameters:
#
# Dependencies:
# - apache:tasks:main
#
# Creates:
#
# File modifications:
# - /etc/php5/apache2/php.ini
#
###############################################################################

# Extract candiate PHP version
- name: install | Detect if PHP 5.4 is available in the repository
  shell:
    "apt-cache policy php5 | grep ': 5.4'"
  ignore_errors: true
  register: php_version_available
  changed_when: php_version_available.rc != 0
  tags:
    - php-config

- name: 'install | Add the PHP 5.4 PPA, current is {{ php_version_avaiable.stdout }}'
  apt_repository:
    repo=ppa:ondrej/php5-oldstable
  when: php_version_available|failed
  tags:
    - php-config

- name: install | Install required php packages
  apt:
    pkg={{ item }}
    state=installed
  with_items:
    - php5
    - php5-curl
    - php5-dev
    - php5-mysqlnd
    - php5-xmlrpc
    - php5-gd
    - php5-cli
    - php5-imagick
    - php5-common
  tags:
    - php-config

- name: "config | Configuration file: /etc/php5/apache2/php.ini"
  template:
    src=php.ini.j2
    dest=/etc/php5/apache2/php.ini
    owner=root group=root
  notify: restart php
  tags:
    - php-config
