---
# Part: PHP
#
# Description: Install XDebug from PECL and configure it together with
# webgrind as a frontend. The frontend is only accessable to localhost so users
# should use tunneling.
#
# Parameters:
#
# Dependencies:
# - tasks:setup
# - tasks:pecl: Used to install PECL packages.
# - apache:tasts:main: Apache should be installed.
# - apache:tasks:vhost-local-alias: Manage localhost only accessable vhost alias
#
# Creates:
# - /opt/webgrind: Git clone of webgrind.
# - {{ vhost_local.url }}/webgrind: Localhost only access to webgrind
#
# File modifications:
# - /etc/php5/conf.d/xdebug.init
#
###############################################################################

- include: pecl.yml
  vars:
    package: xdebug
    version: stable
  tags:
    - php-dev
    - xdebug
    - install

- name: PHP | XDebug | Download webgrind source tarball: /tmp/webgrind.tar.gz
  get_url:
    url={{ xdebug.webgrind.tarball }}
    sha256sum={{ xdebug.webgrind.sha256sum }}
    dest=/tmp/webgrind.tar.gz
    mode=0440
  tags:
    - php-dev
    - xdebug
    - webgrind
    - install

- name: PHP | XDebug | Create /opt/webgrind
  file:
    path=/opt/webgrind
    state=directory
  tags:
    - php-dev
    - xdebug
    - webgrind
    - install

- name: PHP | XDebug | Extract source to /opt/webgrind
  command:
    # Strip first directory and extract its content
    tar -xzf /tmp/webgrind.tar.gz --strip 1 -C /opt/webgrind/
    creates=/opt/webgrind/index.php
  tags:
    - php-dev
    - xdebug
    - webgrind
    - install

- name: PHP | XDebug | Delete tarball /tmp/webgrind.tar.gz
  file:
    path=/tmp/webgrind.tar.gz
    state=absent
  tags:
    - php-dev
    - xdebug
    - webgrind
    - clean

# Manage local vhost alias for /webgrind
- include: ../../apache/tasks/vhost-local-alias.yml
  vars:
    docroot: /opt/webgrind
    alias: /webgrind
    remove: not xdebug.enabled
  tags:
    - php-dev
    - xdebug
    - webgrind
    - config

- name: PHP | XDebug | Configure: /etc/php5/conf.d/xdebug.ini
  lineinfile:
    dest=/etc/php5/conf.d/xdebug.ini
    regex="^{{ item[0] }}"
    line="{{ item[0] }} = {{ item[1] }}"
  notify: restart php
  with_items:
    ['xdebug.profiler_enable_trigger', {{ xdebug.enabled }}]
    ['xdebug.profiler_output_dir', '/tmp']
    ['xdebug.profiler_output_name', 'cachegrind.out.%t.%p']
    ['xdebug.max_nesting_level', 150]
  tags:
    - php-dev
    - xdebug
    - config
    - webgrind
