---
# Part: PHP
#
# Description: Install XDebug from PECL and configure it together with
# webgrind as a frontend. The frontend is only accessable to localhost so users
# should use tunneling.
#
# Parameters:
#
# Dependencies:
# - tasks:setup
# - tasks:pecl: Used to install PECL packages.
# - apache:tasts:main: Apache should be installed.
# - apache:tasks:vhost-local-alias: Manage localhost only accessable vhost alias
#
# Creates:
# - /opt/webgrind: Git clone of webgrind.
# - {{ vhost_local.url }}/webgrind: Localhost only access to webgrind
#
# File modifications:
# - /etc/php5/conf.d/xdebug.init
#
###############################################################################

# Used in conf.d/xdebug.ini.j2
- name: xdebug | Fetch PHP extension dir
  shell: "php -i | grep -i '^extension_dir' | awk '{print $3}'"
  register: php_extension_dir
  changed_when: false
  tags:
    - php-dev
    - xdebug
    - install

- include: pecl.yml
  vars:
    package: xdebug
    version: stable

- include: ../../common/tasks/source-install.yml
  vars:
    name: webgrind
    tarball: '{{ webgrind_install.tarball }}'
    sha256sum: '{{ webgrind_install.sha256sum }}'
    strip: 1
    creates: index.php

# Manage local vhost alias for /webgrind
- include: ../../apache/tasks/vhost-local-alias.yml
  vars:
    docroot: /opt/webgrind
    alias: /webgrind
    enabled: '{{ php.xdebug.enabled }}'
