---
# Part: PHP
#
# Description: Install XhProf from PECL and configure it. Also set up a virtual
# host for the xhprof_html interface, only accessable to localhost.
#
# Parameters:
#
# Dependencies:
# - tasks:setup
# - tasks:pecl: Used to install PECL packages
# - apache:tasks:main: Apache should be installed.
# - apache:tasks:vhost-local-alias: Manage localhost only accessable vhost alias
#
# Creates:
# - /opt/xhprof: Cheatsheet for xhprof usage
# - /opt/xhprof/output: Analysis data for xhprof runs.
# - {{ vhost_local.url }}/xhprof: Localhost only access to xhprof
#
# File modifications:
# - /etc/php5/conf.d/xhprof.init
##
###############################################################################

- include: pecl.yml
  vars:
    package: xhprof
    version: beta
  tags:
    - php-xhprof

- name: "xhprof | Create xhprof cheatsheet directory: /opt/xhprof"
  file:
    path=/opt/xhprof
    state=directory
  tags:
    - php-xhprof

- name: "xhprof | Put xhprof quick loading header and footer + usage instructions in: /opt/xhprof"
  template:
    src=xhprof/{{ item }}.j2
    dest=/opt/xhprof/{{ item }}
  with_items:
    - footer.php
    - header.php
    - notes.txt
  tags:
    - php-xhprof

- name: "xhprof | Install graphviz for execution flow plotting by XhProf"
  apt:
    pkg=graphviz
    state=installed
  tags:
    - php-xhprof

- name: "xhprof | Create xhprof output directory {{ php.xhprof.output_dir }}"
  # @TODO www-data?
  file:
    path={{ php.xhprof.output_dir }}
    state=directory
  tags:
    - php-xhprof

# Manage local vhost alias for /xhprof
- include: ../../apache/tasks/vhost-local-alias.yml
  vars:
    docroot: '{{ php.pecl.install_dir }}/xhprof_html'
    alias: /xhprof
  tags:
    - php-xhprof
    - webui
