---
# Part: Drush
#
# Description: Install drush development modules
#
# Modules:
# - https://drupal.org/project/cacheaudit
# - https://drupal.org/project/drush-hosts
# - https://drupal.org/project/clean_missing_modules
# - https://drupal.org/project/module_builder
# - https://drupal.org/project/coder
#
# Parameters:
#
# Dependencies:
# - tasks:main
# - php:tasks:main
#
# Creates:
# - /var/local/etc/drush/hooks
#
# File modifications:
# - /var/local/etc/drush/drushrc.php
#
###############################################################################

- include: package.yml
  vars:
    packages: '{{ drush.dev.modules }}'
    dir: '{{ drush.dir }}'
  tags:
    - drush-dev

# Module Builder
###

- name: "module builder | config | Set to write code by default: drushrc.php"
  lineinfile:
    dest={{ drush.dir }}/drushrc.local.php
    line="\$command_specific['mb-build']['write'] = TRUE;"
    state=present
  tags:
    - drush-dev

- name: "module builder | config | Check if hook directory is present: {{ drush.dir }}/hooks"
  file:
    path={{ drush.dir }}/hooks
    state=directory
  tags:
    - drush-dev

- name: "module builder | config | Add hooks data directory: drushrc.php"
  lineinfile:
    dest={{ drush.dir }}/drushrc.local.php
    line="\$options['data'] = \"{{ drush.dir }}/hooks\";"
    state=present
  tags:
    - drush-dev

# Coder
###
- name: coder | Find out pear php_dir
  command: pear config-get php_dir
  changed_when: false
  register: php_dir
  tags:
    - drush-dev

- name: coder | config | Symlink Drupal CoderSniffer standard to PHPCS standards
  file:
    src={{ drush.dir }}/coder/coder_sniffer/Drupal
    dest={{ php_dir.stdout }}/PHP/CodeSniffer/Standards/Drupal
    state=link
  tags:
    - drush-dev
