---
# Part: Drush
#
# Description: Sets up drush with extra modules and global config defaults.
#
# Parameters:
#
# Dependencies:
# - php:tasks:pear
#
# Creates:
# - /usr/local/etc/drush
# - /usr/local/etc/drush/dump
#
# File modifications:
# - /usr/local/etc/drush/drushrc.php
#
###############################################################################

- include: ../../php/tasks/pear.yml
  vars:
    package: pear.drush.org/drush

- name: install | Run drush once so it downloads it's dependencies
  command: drush
  ignore_errors: yes
  changed_when: false
  tags:
    - install

- name: config | Ensure global drush directory is present
  file:
    path={{ drush.dir }}
    state=directory
  tags:
    - config

- name: config | Ensure dump drush directory is present
  file:
    path={{ drush.config.dump_dir }}
    state=directory
  tags:
    - config

- name: config | Add global drushrc.php
  template:
    src=drushrc.php.j2
    dest={{ drush.dir }}/drushrc.php
    owner=root group=admin mode=0664
  tags:
    - config

- name: config | Add global drushrc.local.php
  copy:
    src=drushrc.local.php
    dest={{ drush.dir }}/drushrc.local.php
    owner=root group=admin mode=0664
    force=no
  tags:
    - config

# Install drush development modules
- include: drush-dev.yml
  when: drush.dev.install
