---
# Part: WP CLI
#
# Description: Install wp-cli together with global bash completion.
#
# @TODO permissions?
#
# Parameters:
#
# Dependencies:
#
# Creates:
# - /usr/local/lib/wp
# - /usr/local/bin/wp
# - /etc/bash_completion.d/wp
#
# File modifications:
#
###############################################################################
- name: install | Check if version is current
  shell: wp --version | grep 'WP-CLI {{ wpcli_install.version }}'
  register: wp_uptodate
  changed_when: wp_uptodate.rc != 0
  failed_when: false
  ignore_errors: true
  tags:
    - wpcli-config

- name: "install | Download install script /tmp/wpcli-install.sh"
  get_url:
    url={{ wpcli_install.script }}
    sha256sum={{ wpcli_install.sha256sum }}
    dest=/tmp/wpcli-install.sh
    mode=0700
  when: wp_uptodate|failed
  tags:
    - wpcli-config

- name: "install | Run install script"
  shell:
    INSTALL_DIR={{ wpcli.dir }} /tmp/wpcli-install.sh
    creates={{ wpcli.dir }}/bin/wp
  when: wp_uptodate|failed
  tags:
    - wpcli-config

- name: "install | Remove install script: /tmp/wpcli-install.sh"
  file:
    path=/tmp/wpcli-install.sh
    state=absent
  tags:
    - wpcli-config

- name: "install | Create symlink to binary: /usr/bin/wp"
  file:
    src={{ wpcli.dir }}/bin/wp
    dest=/usr/bin/wp
    state=link
  tags:
    - wpcli-config

- include: wp-cli_completion.yml
  vars:
    bash_completion_dir: /etc/bash_completion.d
