---
# Used while securing /dev/shm
- name: reload fstab
  command: mount -a

- name: restart denyhosts
  service:
    name=denyhosts
    state=restarted

- name: restart ssh
  service:
    name=ssh
    state=restarted

- name: reload sysctl
  command: sysctl -p
